name: .NET Core

on:
  push:
    paths:
    - 'api/**.cs'
    - '.github/workflows/dotnetcore.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build with dotnet
      working-directory: ./api
      run: |
        cd /usr/share/dotnet/packs/Microsoft.NETCore.App.Host.linux-x64/
        ls -l
        dotnet build --configuration Release
